### PR TITLE
Unhandled exception in IE older than v9 when loading polymaps.js

### PR DESCRIPTION
**Pull request by jasondavies**
See issue #46. Not sure if it's possible to attach a pull request to existing issues.

### CODE REVIEW

**Comment by jasondavies** [comment]
_bump_ :-)

**Comment by mbostock** [comment]
Do you want to fix the `overrideMimeType` error too? Heh. :)

**Comment by jasondavies** [comment]
Ah, I'd forgotten about that one :-)

**Comment by jasondavies** [comment]
I've fixed it too in this pull request btw, as it probably wasn't obvious from my last comment.

**Comment by mbostock** [comment]
Yep, looks good. 2.5.1 incoming, when I get a minute.

**Pull request merged**
