### PR TITLE
Hash enhancements

### PR DESCRIPTION
**Pull request by jasondavies**
Add `parse` and `format` properties to `po.hash()`.

### CODE REVIEW

**Comment by mbostock** [comment]
Thanks for the contribution!

I just chatted with Tom in IM. I think the names "parser" and "formatter" would better convey that these are properties you are setting on the hash object, rather than verbs to parse or to format.

Also, I tend to think that the parser and formatter should be symmetrical. So, if the formatter calls the map getters and returns a string, the parser should take a string and call the map setters. Then the parser wouldn't have to return an array, and we wouldn't have to define a specific data structure for what the parser returns. And it would be a little cleaner to store whatever data you want in the hash.

**Comment by mbostock** [comment]
Also, yeah, this should bump the minor version number to 2.4.0.

**Comment by jasondavies** [comment]
Thanks for the feedback. Should `parser` take an additional argument: `map` in that case?

**Comment by mbostock** [comment]
Yep, exactly: a parser takes two arguments, a map and a string. And the nice thing about that is that you can make the default implementations static globals, since they won't depend on any of the internal state of the hash control.

Although, I guess then the parser needs a way to communicate that the specified string was invalid, so the hash control can reset the location using the formatter. I guess we could have the parser return true if the string's invalid, triggering a call to `move`? That has the nice property that if you do nothing (returning undefined), the hash control does nothing. Throwing an exception would be the more formal way of doing it but it feels like overkill, at least for now. Hrm.

For example:

```
function hash_parser(map, s) {
  var args = s.split("/").map(Number);
  if (args.length < 3 || args.some(isNaN)) return true; // replace bogus hash
  var size = map.size();
  map.zoomBy(args[0] - map.zoom(),
      {x: size.x / 2, y: size.y / 2},
      {lat: Math.min(lat, Math.max(-lat, args[1])), lon: args[2]});
}

function hash_formatter(map) {
  var center = map.center(),
      zoom = map.zoom(),
      precision = Math.max(0, Math.ceil(Math.log(zoom) / Math.LN2));
  return "#" + zoom.toFixed(2)
      + "/" + center.lat.toFixed(precision)
      + "/" + center.lon.toFixed(precision);
}
```

Then inside the hash control constructor, you can initialize `parser` and `formatter` to point to these globals.

**Comment by jasondavies** [comment]
Not sure if GitHub notifies people of this, but I've pushed all the suggestions above into this pull request now, so feel free to review/modify/pull at your leisure.

**Comment by mbostock** [comment]
Looks great! I'll pull this code in shortly.

**Comment by RandomEtc** [comment]
Just a note to say that although I was notified of the original pull request I didn't get notified that this conversation was happening (maybe there's a setting I missed). I was feeling bad for not getting back to this sooner but I'm happy to see Mike picked it up!

Jason - thanks for making the changes Mike requested. We talked a lot about details like this while polymaps was being written and Mike has a good eye for consistency!

Mike if you want me to do the merge let me know!

**Comment by mbostock** [comment]
Oh, yeah. Sorry I haven't gotten around to it yet. If you want to do it, Tom, that would be much appreciated!

**Comment by RandomEtc** [comment]
I'll give it a go!

**Comment by RandomEtc** [comment]
OK, this is done. I also created v2.4.0 tag and updated the gh-pages branch with bumped version numbers, new download links and some docs for the new functions. Corrections welcome!

**Pull request merged**
