### PR TITLE
Add new layer for panning the map with a scroll wheel or touchpad

### PR DESCRIPTION
**Pull request by bentomas**
Addresses the comments of issue #51

### CODE REVIEW

**Comment by bentomas** [comment]
This does do user agent fishing to know whether to try and do things generically or use Mozilla's proprietary mouse wheel functions.  Other than that it works on feature detection.

**Comment by mbostock** [comment]
Have you seen the new `po.wheel` implementation in 2.5.0? I'm using the same technique. See commit @4518c22864c1c30540e4. I'm tempted to just bake this functionality into the existing wheel implementation, enabled by a flag. Say, `po.wheel().zoom("pan")`?

I didn't do any user-agent detection in `po.wheel`, since I assume event types that are unknown are ignored.

**Comment by bentomas** [comment]
I did see the po.wheel implementation!  It looks good!

I just really don't like that functionality.  Panning feels so much more natural than zooming to me, when using a mouse wheel or trackpad (on Macs at least).  

Is this 'pan' mode you mention something that you want to implement? I can take a stab at it if you'd like.  I agree that you probably don't have to do user-agent detection.

**Comment by mbostock** [comment]
Right, I'm suggesting you take your new functionality (in `po.wheelPan`) and bake it into `po.wheel`, where it would be enabled by saying `zoom("pan")`. This way, you could use the existing event listeners and hidden divs for dispatching; you'd just change the behavior.

I'm not totally sure that `zoom("pan")` is the right name for the flag, but it seems to fit in reasonably well to what's there already. If you want to enable it some other way, let me know!

**Comment by RandomEtc** [comment]
What about `po.wheel("pan")` implying `po.wheel("zoom")` would be the default?

**Comment by mbostock** [comment]
As a constructor argument? Avoid the naming issue altogether ya? Ha! :) But then you'd still have a `zoom` property, which wouldn't make sense in pan mode. Also, it's nice to be able to change the behavior without creating a new instance.

Renaming the `zoom` property to `mode` would probably be the cleanest. Alas, that would not be backwards-compatible, so `zoom("pan")` still seems reasonable.

**Comment by mbostock** [comment]
I suppose you could avoid registering the `zoom` property if the `po.wheel("pan")` constructor is used, which is the nice thing about these class-less objects. So, either way. :)

**Comment by bentomas** [comment]
I'm closing this pull request in light of my latest pull request: 

https://github.com/simplegeo/polymaps/pull/67

**Pull request closed without merging**
